services:
  spotify-discord-show-episodes-webhook:
    image: "ghcr.io/wissididom/spotify-discord-show-episodes-webhook"
    restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file: .env
