name: Deno Formatting

on:
  push:
    branches: ["master", "main", "develop"]
  pull_request:

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies
        run: |
          deno install
      - name: Check format
        run: |
          deno fmt
          git --no-pager diff --exit-code --color=never
